## tentativa 1

name: Build and deploy JAR app to Azure Web App - app-procurement

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v2  # Updated to use v2 and Node.js 20
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CCF2111C2C2A4A4A9DFB6B432C64081B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2AEA9D90035A46BF9C8CDBC0EC3AEDB5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_83F35A71A9464F40840BB4F7ECD31CEA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-procurement'
          slot-name: 'Production'
          package: '*.jar'



## default do azure:
## Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
## More GitHub Actions for Azure: https://github.com/Azure/actions
#
#name: Build and deploy JAR app to Azure Web App - app-procurement
#
#on:
#  push:
#    branches:
#      - main
#  workflow_dispatch:
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up Java version
#        uses: actions/setup-java@v1
#        with:
#          java-version: '17'
#
#      - name: Build with Maven
#        run: mvn clean install
#
#      - name: Upload artifact for deployment job
#        uses: actions/upload-artifact@v3
#        with:
#          name: java-app
#          path: '${{ github.workspace }}/target/*.jar'
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'Production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#    permissions:
#      id-token: write #This is required for requesting the JWT
#
#    steps:
#      - name: Download artifact from build job
#        uses: actions/download-artifact@v3
#        with:
#          name: java-app
#
#      - name: Login to Azure
#        uses: azure/login@v1
#        with:
#          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CCF2111C2C2A4A4A9DFB6B432C64081B }}
#          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2AEA9D90035A46BF9C8CDBC0EC3AEDB5 }}
#          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_83F35A71A9464F40840BB4F7ECD31CEA }}
#
#      - name: Deploy to Azure Web App
#        id: deploy-to-webapp
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: 'app-procurement'
#          slot-name: 'Production'
#          package: '*.jar'
#